# ACT Policy Training Configuration
# Train Action Chunking Transformer (native getiaction implementation)
#
# Usage:
#   getiaction fit --config configs/getiaction/act.yaml

model:
  class_path: getiaction.policies.ACT

data:
  class_path: getiaction.data.lerobot.LeRobotDataModule
  init_args:
    repo_id: "lerobot/pusht"
    train_batch_size: 64
    data_format: "getiaction"
    val_gym:
      class_path: getiaction.gyms.pusht.PushTGym
    image_transforms:
      class_path: torchvision.transforms.v2.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.v2.ColorJitter
            init_args:
              contrast:
                - 0.8
                - 1.2
              brightness:
                - 0.7
                - 1.3

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  precision: 32
  log_every_n_steps: 100
  check_val_every_n_epoch: 10
