# ACT Policy Training Configuration
# Train Action Chunking Transformer (native physicalai implementation)
#
# Usage:
#   physicalai fit --config configs/physicalai/act.yaml

model:
  class_path: physicalai.policies.ACT

data:
  class_path: physicalai.data.lerobot.LeRobotDataModule
  init_args:
    repo_id: "lerobot/pusht"
    train_batch_size: 64
    data_format: "physicalai"
    val_gym:
      class_path: physicalai.gyms.pusht.PushTGym
    image_transforms:
      class_path: torchvision.transforms.v2.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.v2.ColorJitter
            init_args:
              contrast:
                - 0.8
                - 1.2
              brightness:
                - 0.7
                - 1.3

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  precision: 32
  log_every_n_steps: 100
  check_val_every_n_epoch: 10
