blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/open-edge-platform/geti-action/discussions
    about: Ask questions or start discussions here
  - name: Security Vulnerability
    url: https://github.com/open-edge-platform/geti-action/security/advisories/new
    about: Report security vulnerabilities privately
