name: Backend
on:
  push:
    branches:
      - "main"
  pull_request:

permissions: {} # No permissions by default on workflow level

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - &set-up-python
        name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "./application/backend/.python-version"

      - name: Run prek
        uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1
        with:
          extra-args: --all-files
          working-directory: application/backend

  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - *checkout

      - *set-up-python

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: "0.8.8"

      - name: Prepare venv and install Python dependencies
        working-directory: application/backend
        run: |
          uv lock --check
          uv sync --frozen --all-extras

      - name: Check source code with mypy
        working-directory: application/backend
        run: |
          uv run mypy . --config-file=pyproject.toml
