name: Backend
on:
  push:
    branches:
      - "main"
  pull_request:

permissions: {} # No permissions by default on workflow level

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - &set-up-python
        name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: "./application/backend/.python-version"

      - name: Run prek
        uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1
        with:
          extra-args: --all-files
          working-directory: application/backend

  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - *checkout

      - *set-up-python

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          version: "0.8.8"

      - name: Prepare venv and install Python dependencies
        working-directory: application/backend
        run: |
          uv lock --check
          uv sync --frozen --all-extras

      - name: Check source code with mypy
        working-directory: application/backend
        run: |
          uv run mypy . --config-file=pyproject.toml
