name: Docker Build

on:
  pull_request:
    branches: [main]
    paths:
      - "library/**"
      - "application/**"
      - ".github/actions/docker-build/**"
      - ".github/workflows/docker-build.yml"

permissions: {} # No permissions by default on workflow level

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io/open-edge-platform/physical-ai-studio/dev

jobs:
  build:
    name: Build (${{ matrix.device }})
    runs-on: ubuntu-latest
    permissions:
      contents: read # Checkout code

    strategy:
      fail-fast: false
      matrix:
        device: [cpu, xpu, cuda]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          device: ${{ matrix.device }}
          registry: ${{ env.REGISTRY }}

      - name: Upload Docker image
        if: matrix.device != 'cuda'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: physical-ai-studio-${{ matrix.device }}
          path: ${{ runner.temp }}/physical-ai-studio-${{ matrix.device }}.tar
          retention-days: 7
