name: Geti Action training
permissions: {} # No permissions by default on workflow level

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch: # run on request (no need for PR)

jobs:
  code-quality:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: "./library/.python-version"
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      - name: Verify lock file
        working-directory: library
        run: uv lock --check
      - name: Install dependencies
        working-directory: library
        run: |
          uv sync --frozen --all-extras
      - name: Run pre-commit checks
        working-directory: library
        run: |
          uv run pre-commit run --all-files
  unit-tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: "./library/.python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      - name: Verify lock file
        working-directory: library
        run: uv lock --check
      - name: Install dependencies
        working-directory: library
        run: |
          uv sync --frozen --all-extras
      - name: Run python unit tests
        working-directory: library
        run: |
          uv run pytest tests/unit
