name: Geti Action server checks
on:
  push:
    branches: ["main"]
  pull_request:

permissions: {} # No permissions by default on workflow level

jobs:
  python-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          version: "0.8.8"

      - name: Prepare venv and install Python dependencies
        working-directory: application/backend
        run: |
          uv lock --check
          uv sync --frozen --all-extras

      - name: Check formatting with ruff
        working-directory: application/backend
        run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check .

      - name: Check source code with mypy
        working-directory: application/backend
        run: |
          uv run mypy . --config-file=pyproject.toml
