name: UI
permissions: {} # No permissions by default on workflow level

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: # run on request (no need for PR)

jobs:
  generate-openapi-spec:
    name: Generate OpenAPI Spec
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "./application/backend/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          version: "0.10.4"

      - name: Install OpenCV dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Prepare venv and install Python dependencies
        working-directory: application/backend
        run: |
          uv lock --check
          uv sync --frozen --extra cpu

      - name: Get OpenAPI spec
        working-directory: application/backend
        run: |
          export PYTHONPATH=.
          uv run src/cli.py gen-api --target-path openapi-spec.json

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: openapi-spec
          path: application/backend/openapi-spec.json

  build:
    name: Build UI
    needs:
      - generate-openapi-spec
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - &checkout
        name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - &setup-node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        id: setup-node
        with:
          node-version-file: application/ui/.nvmrc

      - &install-dependencies
        name: Install dependencies
        working-directory: "application/ui"
        run: npm ci


      - &download-openapi-spec
        name: Download OpenAPI spec artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: openapi-spec
          path: application/ui/src/api

      - &build-openapi-types-definitions
        name: Build OpenAPI type definitions
        working-directory: "application/ui"
        run: npm run build:api

      - name: Build UI
        working-directory: "application/ui"
        run: npm run build

      - name: Compress build
        working-directory: "application/ui"
        run: tar -czf dist.tar.gz dist

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ui-dist
          path: "application/ui/dist.tar.gz"

  lint:
    name: Eslint checks
    needs:
      - generate-openapi-spec
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - *checkout

      - *setup-node

      - *install-dependencies

      - *download-openapi-spec

      - *build-openapi-types-definitions

      - name: Prettier
        working-directory: "application/ui"
        run: npm run format:check

      - name: Eslint
        working-directory: "application/ui"
        run: npm run lint

      - name: Eslint cyclic imports
        working-directory: "application/ui"
        run: npm run cyclic-deps-check

      - name: Typescript
        working-directory: "application/ui"
        run: npm run type-check

  unit-tests:
    name: Unit tests
    needs:
      - generate-openapi-spec
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - *checkout

      - *setup-node

      - *install-dependencies

      - *download-openapi-spec

      - *build-openapi-types-definitions

      - name: UI Unit tests
        working-directory: "application/ui"
        run: npm run test:unit

  playwright-tests:
    name: Playwright Tests
    needs:
      - build
      - generate-openapi-spec
    permissions:
      contents: read # to checkout code
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy@sha256:6aca677c27a967caf7673d108ac67ffaf8fed134f27e17b27a05464ca0ace831
    steps:
      - *checkout

      - *setup-node

      - *install-dependencies

      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ui-dist
          path: "application/ui"

      - name: Unpack build
        working-directory: "application/ui"
        run: tar -xzf dist.tar.gz

      - *download-openapi-spec

      - *build-openapi-types-definitions

      - name: Run Playwright tests
        working-directory: "application/ui"
        run: npm run test:component -- --project "Component tests"

      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: always()
        with:
          name: playwright-report
          path: application/ui/playwright-report/
          retention-days: 30
